### PR TITLE
refactor and fix: Move away from bulk delete to bulk edit strategy

### LINKED ISSUE #3: Move away from bulkDelete in the channel to bulkEdit solution
Discord bulk delete has certain limitations and reliability issues which weren't accounted for. This will require changing the code to move away from bulk delete. 

### Solution
Move to an incremental edit approach. 

On new changes to FAQ directory, fetch the files and entries which would need to be posted. Calculate the number of messages you would need for the entries (check for existing messages by the bot in the channel). For example, for 10 faqs - you will require 12 messages. One for index and one for wiki at the end. 

Check if there are enough messages, if not add new message at the bottom. Then stream the edit sequentially. This approach doesn't require any database or mapping to maintain but should result in two notifications at most (if the index gets bigger, will need to split it into two). 

Put a condition check to only trigger the action if the base directory from the glob is concerned.

### PR DESCRIPTION
**Pull request by zulienthegreat**
closes #3

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -61,17 +61,43 @@ async function run() {
...
-
-      info(`${channel.name} channel wiped`);
-
-      const sentEmbeds = await Promise.all(
-        embeds.map((embed) => channel.send(embed))
-      );
+      info(`Resolving messages in the channel: ${channel.name} in ${channel.guild.name}`);
+
+      const messages = await channel.messages.fetch({
+        limit: 100
```
Comment (crimelabs786) [inline src/index.ts:67]: Why are we assuming it'd be 100 / 100 is a good enough number?

Also, let's not have magic number in code like these. Gets harder to refactor & extend later. Define it as a constant above the file, say `MESSAGE_FETCH_LIMIT` and then use it here.

File: src/index.ts [hunk 2]
```diff
@@ -61,17 +61,43 @@ async function run() {
...
+      info(`Number of messages required: ${messagesRequired}`)
+
+      if(messagesRequired > botMessages.size) {
+        const pendingMessages = messagesRequired - botMessages.size
+        info(`Number of messages required to operate: ${pendingMessages}`)
+
+        const newMessages = await Promise.all(new Array(pendingMessages).fill(0).map((_, index) => channel.send(new MessageEmbed())))
+        info(`${newMessages.length} messages sent.`)
+        newMessages.map((item => botMessages.set(item.id, item)))
+      } else if(botMessages.size > messagesRequired) {
```
Comment (crimelabs786) [inline src/index.ts:87]: What happens if `botMessages.size === messagesRequired` ? That seems to be the only case not handled here. Can we removed the `else if (...)` with `else`?

Comment (zulienthegreat) [reply src/index.ts:87]: Nothing should happen.

File: src/index.ts (hunk 1 above)
Comment (zulienthegreat) [reply src/index.ts:67]: That's the upper limit on how many messages you can fetch in one swoop. Don't think we need to go beyond that any time soon and if we do, then only wiki should be linked because > 100 of embeds in a single discord channel ain't good UX. It will only return the real number of messages back.

File: src/index.ts [hunk 3]
```diff
@@ -61,17 +61,43 @@ async function run() {
...
+
+      const messagesRequired = countMessagesRequired(embeds)
+      
+      info(`Number of messages required: ${messagesRequired}`)
+
+      if(messagesRequired > botMessages.size) {
+        const pendingMessages = messagesRequired - botMessages.size
+        info(`Number of messages required to operate: ${pendingMessages}`)
+
+        const newMessages = await Promise.all(new Array(pendingMessages).fill(0).map((_, index) => channel.send(new MessageEmbed())))
```
Comment (crimelabs786) [inline src/index.ts:84]: `new` is not needed. But I'd prefer promise array construction be kept separate.

```ts
const messageEmbedPromises = Array(pendingMessages)
  .fill(0)
  .map((_, index) => channel.send(new MessageEmbed()));

const newMessages = await Promise.all(messageEmbedPromises);
```

Comment (zulienthegreat) [reply src/index.ts:84]: Using new is just convention since some inbuilt object constructor shouldn't be used directly.

File: src/index.ts [hunk 4]
```diff
@@ -61,17 +61,43 @@ async function run() {
...
+        info(`${newMessages.length} messages sent.`)
+        newMessages.map((item => botMessages.set(item.id, item)))
+      } else if(botMessages.size > messagesRequired) {
+        const messagesToDestroy = botMessages.last(botMessages.size - messagesRequired)
+        
+        info(`Destroying last ${messagesToDestroy.length} messages.`)
+        
+        await Promise.all(new Array(messagesToDestroy.length).fill(0).map((_, index) => channel.messages.delete(messagesToDestroy[index])))
```
Comment (crimelabs786) [inline src/index.ts:92]: Same as [above](https://github.com/indiainvestments/faq-to-discord-action/pull/4/files?file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.ts&file-filters%5B%5D=dotfile#r572977325)

File: src/index.ts [hunk 5]
```diff
@@ -61,17 +61,43 @@ async function run() {
...
+        messagesToDestroy.map(m => botMessages.delete(m.id))
```
Comment (crimelabs786) [inline src/index.ts:93]: Don't use `map` when you're not using the returned array, use `forEach`. Or better yet, use `for of` loop.

File: src/index.ts [hunk 6]
```diff
@@ -82,30 +108,43 @@ async function run() {
 
       info(`Wiki url is at: ${websiteBaseUrl}`);
 
-      const messagePathIndice = messagePaths.reduce<string[]>(
+      const embedPathIndice = embedPaths.reduce<string[][]>(
         (pathIndice, item, index) => {
```
Comment (crimelabs786) [inline src/index.ts:112]: Spelling error, should be `pathIndices`, not `pathIndice`

File: src/index.ts [hunk 7]
```diff
@@ -82,30 +108,43 @@ async function run() {
...
-          pathIndice.push(`${index + 1}. [${item.title}](${item.link})`);
+          const entry = `${index + 1}. [${item.title}](${item.link})`
+          if(Array.isArray(pathIndice[pathIndice.length-1])) {
```
Comment (crimelabs786) [inline src/index.ts:114]: We seem to be accessing last element of the array quite a lot.

Ruby has `first`, `last`, which for some reason we don't have in JS.

Let's define it ourselves

```ts
Array.prototype.last = Array.prototype.last || function() {
  const array = this;
  const { length } = array;
  return array[(length - 1)];
}
```

Then invoke it on arrays.

Comment (zulienthegreat) [reply src/index.ts:114]: eh, no need and I would rather not have any prototypical modifitication in the code.

File: src/index.ts [hunk 8]
```diff
@@ -82,30 +108,43 @@ async function run() {
...
+            if(pathIndice[pathIndice.length-1].length >= 10) {
```
Comment (crimelabs786) [inline src/index.ts:115]: 10 is a magic number, define is a constant above the file, like `MESSAGE_EMBED_PAYLOAD_MAX_.

File: src/util.ts [hunk 9]
```diff
@@ -48,3 +40,8 @@ export function truncate(text: string, max: number, suffix: string) {
         text.substr(0, max - suffix.length).lastIndexOf(" ")
       )}${suffix}`;
 }
+
+export function countMessagesRequired<T>(items: T[]) {
+  const indexCount = items.filter((_, index) => !(index % 10)).length
```
Comment (crimelabs786) [inline src/util.ts]: Not sure I understood the logic here.

For instance, if I've an array of 35 entries, then the first line keeps elements in these positions: [0, 10, 20, 30]. Length of this is 4. Which is same as `Math.ceil(items.length / 10)`. Is this not correct, or am I mistaking something / not considering an edge case?

File: yarn.lock [hunk 10]
```diff
@@ -50,14 +67,95 @@
...
+  version "6.8.2"
+  resolved "https://registry.yarnpkg.com/@octokit/types/-/types-6.8.2.tgz#ce4872e038d6df38b2d3c21bc12329af0b10facb"
+  integrity sha512-RpG0NJd7OKSkWptiFhy1xCLkThs5YoDIKM21lEtDmUvSpbaIEfrxzckWLUGDFfF8RydSyngo44gDv8m2hHruUg==
   dependencies:
-    "@types/unist" "*"
+    "@octokit/openapi-types" "^4.0.0"
+    "@types/node" ">= 8"
 
-"@types/node@^14.14.22":
+"@types/node@>= 8", "@types/node@^14.14.22":
```
Comment (crimelabs786) [inline yarn.lock:158]: Would recommend running `npx yarn-deduplicate`, to avoid these duplications.

File: yarn.lock [hunk 11]
```diff
@@ -50,14 +67,95 @@
...
+    "@octokit/endpoint" "^6.0.1"
+    "@octokit/request-error" "^2.0.0"
+    "@octokit/types" "^6.7.1"
+    deprecation "^2.0.0"
+    is-plain-object "^5.0.0"
+    node-fetch "^2.6.1"
+    once "^1.4.0"
+    universal-user-agent "^6.0.0"
+
+"@octokit/types@^6.0.3", "@octokit/types@^6.7.1", "@octokit/types@^6.8.0", "@octokit/types@^6.8.2":
```
Comment (crimelabs786) [inline yarn.lock:150]: Same as [above](https://github.com/indiainvestments/faq-to-discord-action/pull/4/files?file-filters%5B%5D=.json&file-filters%5B%5D=.lock&file-filters%5B%5D=.ts&file-filters%5B%5D=dotfile#r572997475)

File: src/index.ts [hunk 12]
```diff
@@ -32,11 +37,12 @@ async function run() {
       )}/${path.name}`;
 
       debug(`Read url for ${file} is at: ${readUrl}`);
+
       return {
         title,
         readUrl,
         description: [
-          truncate(markdown.content, 1800, "..."),
+          truncate(markdown.content, 1700, "..."),
```
Comment (crimelabs786) [inline src/index.ts:45]: Magic number 1700 - should be defined as a constant, and moved to `util`.

**Review by crimelabs786 — CHANGES_REQUESTED** [review]
Overall, I feel this is imperative code, and some repetitive code pattens (just check number of times an array with map has been constructed for promises.

Ideally, it should be broken down in small utility functions (also opens the door to add testing), while the main `run` function combines them all.

Even if it feels like something that's too much in the early stages, I feel we should do this. Happy to take a stab at it. Let's spend 1-2 extra day on this to get it right, our future versions would thank us down the line.

File: src/index.ts (hunk 7 above)
Comment (crimelabs786) [reply src/index.ts]: Ok, we can add a utility function that takes `array` as an input and returns the last element.

File: src/util.ts (hunk 9 above)
Comment (zulienthegreat) [reply src/util.ts]: Good catch. I was doing something else before with the function. Needs to changed.
